Initial Implementation
bluemarblepayroll/file_composer pull request #1
Opened 2020-09-01 16:04 UTC by mattruggio

2020-09-10 16:14 UTC, gerryster requested changes
Most of my comments are fairly minor and several are regarding documentation. One overall thought is the creation of zip files without an enclosing directory. This is a pet peeve of mine. When I extract a zip file which puts its contents in the current directory instead of extracting everything in an enclosing directory, I am irritated about the clutter that was just created. It would be nice if one could specify an enclosing directory for zip files via the blueprint. A similar concern is that even though there is file uniqueness checking at the top level, it would be possible to create a zip file that when extracted, conflicts with other files. For example, modifying your hello_worlds_zip.yaml example:

```
documents:
  - type: text
    filename: hello_world_1.txt
    data: FIRST HELLO WORLD!
  - type: text
    filename: hello_world_2.txt
    data: SECOND HELLO WORLD!
  - type: zip
    filename: nested.zip
    blueprint:
      documents:
        - type: text
          filename: hello_world_1.txt
          data: THIRD HELLO WORLD!
```

Note that I do not get an error about hello_world_1.txt being a duplicate file name. Typically unzip programs warn a user before overwriting a file when extracting. However, it would probably be handy to have some guardrails for Blueprint authors to prevent them from creating scenarios where the end user of the created files has to make an unexpected decision about duplication.

2020-09-10 16:14 UTC, gerryster commented on spec/file_helper.rb
> +  File.open(File.join(*filename), 'rb').read
Why open the YAML file in binary mode?

2020-09-11 02:59 UTC, mattruggio commented on lib/file_composer/documents/zip.rb
> +        physical_filename     = zip!(temp_root, results)
I went back and forth on this one.

2020-09-11 05:12 UTC, mattruggio commented on lib/file_composer/stores/local.rb
> +          FileUtils.cp(filename, final_filename)
Good call

2020-09-11 05:42 UTC, mattruggio commented on lib/file_composer/documents/file_result.rb
> +  class Documents
Outside consumers can register new document types using [ActsAsHashable::Factory#register.](https://github.com/bluemarblepayroll/acts_as_hashable/blob/master/lib/acts_as_hashable/factory.rb#L31)

2020-09-11 18:22 UTC, mattruggio commented
> Most of my comments are fairly minor and several are regarding documentation. One overall thought is the creation of zip files without an enclosing directory. This is a pet peeve of mine. When I extract a zip file which puts its contents in the current directory instead of extracting everything in an enclosing directory, I am irritated about the clutter that was just created. It would be nice if one could specify an enclosing directory for zip files via the blueprint. A similar concern is that even though there is file uniqueness checking at the top level, it would be possible to create a zip file that when extracted, conflicts with other files. For example, modifying your hello_worlds_zip.yaml example:
> 
> ```
> documents:
>   - type: text
>     filename: hello_world_1.txt
>     data: FIRST HELLO WORLD!
>   - type: text
>     filename: hello_world_2.txt
>     data: SECOND HELLO WORLD!
>   - type: zip
>     filename: nested.zip
>     blueprint:
>       documents:
>         - type: text
>           filename: hello_world_1.txt
>           data: THIRD HELLO WORLD!
> ```
> 
> Note that I do not get an error about hello_world_1.txt being a duplicate file name. Typically unzip programs warn a user before overwriting a file when extracting. However, it would probably be handy to have some guardrails for Blueprint authors to prevent them from creating scenarios where the end user of the created files has to make an unexpected decision about duplication.

Let's defer this until we find it becoming an issue.  Technically it does not prevent the library from properly generating the desired files, it only *potentially* affects the user's experience when extracting/downloading files.

2020-09-11 21:15 UTC, gerryster requested changes
Ok, @mattruggio : one very minor copy change idea for you. Also, it looks like the build is failing due to Rubocop. Looks good otherwise!

2020-09-11 21:15 UTC, gerryster commented on lib/file_composer/blueprint.rb
> +      not_unique = filenames.uniq.length != @documents.length
Nice, this is a lot more clear.

2020-09-12 03:20 UTC, mattruggio commented on file_composer.gemspec
> +    This library provides a YAML-based configuration, called a Blueprint, that allows you to specify text files and zip files and it will create them.  It is pluggable so other document types and sto
Looked like rubocop-ast published a new minor version and broke compatibility, I locked in the known compatible one for now.

2020-09-12 03:21 UTC, mattruggio commented on file_composer.gemspec
> +    This library provides a YAML-based configuration, called a Blueprint, that allows you to specify text files and zip files and it will create them.  It is pluggable so other document types and sto
Updated README as well.

2020-09-15 19:56 UTC, gerryster approved these changes

2020-09-16 13:51 UTC, merged